/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MmStickPrice {
        "stockSymbol": string;
    }
    interface MmStockFinder {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMmStickPriceElement extends Components.MmStickPrice, HTMLStencilElement {
    }
    var HTMLMmStickPriceElement: {
        prototype: HTMLMmStickPriceElement;
        new (): HTMLMmStickPriceElement;
    };
    interface HTMLMmStockFinderElement extends Components.MmStockFinder, HTMLStencilElement {
    }
    var HTMLMmStockFinderElement: {
        prototype: HTMLMmStockFinderElement;
        new (): HTMLMmStockFinderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mm-stick-price": HTMLMmStickPriceElement;
        "mm-stock-finder": HTMLMmStockFinderElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MmStickPrice {
        "stockSymbol"?: string;
    }
    interface MmStockFinder {
        "onMmSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mm-stick-price": MmStickPrice;
        "mm-stock-finder": MmStockFinder;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mm-stick-price": LocalJSX.MmStickPrice & JSXBase.HTMLAttributes<HTMLMmStickPriceElement>;
            "mm-stock-finder": LocalJSX.MmStockFinder & JSXBase.HTMLAttributes<HTMLMmStockFinderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
